spring.application.name=spring-boot-mongodb-crud
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mydb

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO